---

# Nexus http://www.sonatype.org/
nexus_url: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-unix.tar.gz
nexus_home: "{{ kenzanmedia_apps }}/sonatype_nexus"
nexus_data: "{{ kenzanmedia_data }}/sonatype_nexus"
nexus_dns: repo.kenzanmedia.build
